framework:
    cache:
        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
